{"name": "CPAG 220 Fundamentals of Public Finance, Budgeting and Reporting (3 credits)", "term": "This course is not scheduled for the 2019-2020 academic year.", "link": "https://mcgill.ca/study/2019-2020/courses/cpag-220", "subject": "CPAG"}
{"name": "CPAG 525 Public Finance, Budgeting and Reporting (3 credits)", "term": "This course is not scheduled for the 2019-2020 academic year.", "link": "https://mcgill.ca/study/2019-2020/courses/cpag-525", "subject": "CPAG"}
{"name": "CPAG 515 Public Regulations and Ethics in the Public Sector (3 credits)", "term": "This course is not scheduled for the 2019-2020 academic year.", "link": "https://mcgill.ca/study/2019-2020/courses/cpag-515", "subject": "CPAG"}
{"name": "CPAG 520 Leadership and Governance in Public Organizations (3 credits)", "term": "This course is not scheduled for the 2019-2020 academic year.", "link": "https://mcgill.ca/study/2019-2020/courses/cpag-520", "subject": "CPAG"}
{"name": "CPAG 500 Lean Operations in Public Services (3 credits)", "term": "This course is not scheduled for the 2019-2020 academic year.", "link": "https://mcgill.ca/study/2019-2020/courses/cpag-500", "subject": "CPAG"}
{"name": "CPAG 410 Strategic Planning and Implementation (3 credits)", "term": "Fall 2019", "link": "https://mcgill.ca/study/2019-2020/courses/cpag-410", "subject": "CPAG"}
{"name": "CPAG 510 Current Issues in Public Sector Management (3 credits)", "term": "This course is not scheduled for the 2019-2020 academic year.", "link": "https://mcgill.ca/study/2019-2020/courses/cpag-510", "subject": "CPAG"}
{"name": "CPAG 305 Current Issues in Public Sector Administration (3 credits)", "term": "This course is not scheduled for the 2019-2020 academic year.", "link": "https://mcgill.ca/study/2019-2020/courses/cpag-305", "subject": "CPAG"}
{"name": "CPAG 300 Lean Operational Practices in Public Services (3 credits)", "term": "This course is not scheduled for the 2019-2020 academic year.", "link": "https://mcgill.ca/study/2019-2020/courses/cpag-300", "subject": "CPAG"}
{"name": "CPAG 225 Foundations of Public Regulations and Ethics in Public Sector (3 credits)", "term": "This course is not scheduled for the 2019-2020 academic year.", "link": "https://mcgill.ca/study/2019-2020/courses/cpag-225", "subject": "CPAG"}
{"name": "CPAG 400 Diversity and Cross Cultural Management (3 credits)", "term": "Fall 2019", "link": "https://mcgill.ca/study/2019-2020/courses/cpag-400", "subject": "CPAG"}
