{"name": "FIGG TL04 Learning to Teach: A Professional Development Workshop for Graduate Students", "term": "This course is not scheduled for the 2019-2020 academic year.", "link": "https://mcgill.ca/study/2019-2020/courses/figg-tl04", "subject": "FIGG"}
{"name": "FIGG WS1 Grantsmanship for Graduate Students", "term": "This course is not scheduled for the 2019-2020 academic year.", "link": "https://mcgill.ca/study/2019-2020/courses/figg-ws1", "subject": "FIGG"}
{"name": "FIGG TL03 Learning to Teach: A Professional Development Workshop for Graduate Students", "term": "This course is not scheduled for the 2019-2020 academic year.", "link": "https://mcgill.ca/study/2019-2020/courses/figg-tl03", "subject": "FIGG"}
{"name": "FIGG TL02 Learning to Teach: A Professional Development Workshop for Graduate Students", "term": "This course is not scheduled for the 2019-2020 academic year.", "link": "https://mcgill.ca/study/2019-2020/courses/figg-tl02", "subject": "FIGG"}
{"name": "FIGG MYR4 Getting Your Research Out", "term": "This course is not scheduled for the 2019-2020 academic year.", "link": "https://mcgill.ca/study/2019-2020/courses/figg-myr4", "subject": "FIGG"}
{"name": "FIGG MYR3 Search Strategies & Techniques", "term": "This course is not scheduled for the 2019-2020 academic year.", "link": "https://mcgill.ca/study/2019-2020/courses/figg-myr3", "subject": "FIGG"}
{"name": "FIGG GS2 Going Deeper: A Professional Development Workshop for Graduate Students", "term": "This course is not scheduled for the 2019-2020 academic year.", "link": "https://mcgill.ca/study/2019-2020/courses/figg-gs2", "subject": "FIGG"}
{"name": "FIGG TL01 Learning to Teach: A Professional Development Workshop for Graduate Students", "term": "This course is not scheduled for the 2019-2020 academic year.", "link": "https://mcgill.ca/study/2019-2020/courses/figg-tl01", "subject": "FIGG"}
{"name": "FIGG MYR1 EndNote Essentials", "term": "This course is not scheduled for the 2019-2020 academic year.", "link": "https://mcgill.ca/study/2019-2020/courses/figg-myr1", "subject": "FIGG"}
{"name": "FIGG GS1 Diving into the Research Pool: A Professional Development Workshop for Graduate Students", "term": "This course is not scheduled for the 2019-2020 academic year.", "link": "https://mcgill.ca/study/2019-2020/courses/figg-gs1", "subject": "FIGG"}
{"name": "FIGG MYR2 Research Tool Kit", "term": "This course is not scheduled for the 2019-2020 academic year.", "link": "https://mcgill.ca/study/2019-2020/courses/figg-myr2", "subject": "FIGG"}
